Link to contract source from imports (draft)
OpenZeppelin/contracts-wizard pull request #102
Opened 2022-03-09 16:40 UTC by ericglau

2022-03-10 00:21 UTC, frangio requested changes

2022-03-10 00:21 UTC, frangio commented on packages/ui/src/App.svelte
> +        const quotes = match[4];
```suggestion
        const [line, ozPrefix, contractsLibrary, relativePath, quotes] = match;
```

2022-03-10 00:21 UTC, frangio commented on packages/ui/src/App.svelte
> +        if (line !== undefined && ozPrefix !== undefined && contractsLibrary !== undefined && relativePath !== undefined && quotes !== undefined) {
We basically know they won't be undefined, right? Otherwise regex wouldn't have matched. We can use non-null assertions like `${contractsLibrary!}`.

2022-03-10 00:21 UTC, frangio commented on packages/ui/src/App.svelte
> +          const replacedImportLine = `<a href='https://github.com/OpenZeppelin/openzeppelin-${contractsLibrary}blob/v${contractsVersion}/contracts/${relativePath}' target='_blank' rel='noopener noref
If we can put the style in a CSS file that would be better.

2022-03-10 00:21 UTC, frangio commented on packages/ui/src/App.svelte
> +      let match = importRegex.exec(code);
Is there a reason why we'd use a while loop instead of just the [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method with a `/g` regex?

2022-03-10 00:21 UTC, frangio commented on packages/ui/src/App.svelte
> +    function injectHyperlinks(code: string) {
Let's move this to a separate file under `utils/`.

2022-03-10 21:31 UTC, ericglau commented on packages/ui/src/App.svelte
> +          const replacedImportLine = `<a href='https://github.com/OpenZeppelin/openzeppelin-${contractsLibrary}blob/v${contractsVersion}/contracts/${relativePath}' target='_blank' rel='noopener noref
Added CSS for links including hover color.  Any opinion on whether we should keep the underlines?  It adds clutter but makes it obvious that it's a link.

![Screen Shot 2022-03-10 at 4 29 02 PM](https://user-images.githubusercontent.com/29640130/157757936-cc7afe3a-a25b-4b2e-abb1-8d167ed4cb8f.png)

2022-03-12 03:25 UTC, frangio commented on packages/ui/src/App.svelte
> +          const replacedImportLine = `<a href='https://github.com/OpenZeppelin/openzeppelin-${contractsLibrary}blob/v${contractsVersion}/contracts/${relativePath}' target='_blank' rel='noopener noref
I think the underline is fine. The blue on hover was a bit much for me... I removed it in the last commit.

2022-03-14 22:26 UTC, frangio approved these changes
LGMT

2022-03-15 13:07 UTC, merged