Clipboard feedback
OpenZeppelin/contracts-wizard pull request #174
Opened 2022-08-25 15:20 UTC by sleepyqadir

- added checkIcon 
- trigger copied feedback on copy to clipboard button

2022-08-25 19:16 UTC, frangio requested changes
Thank you @sleepyqadir! Can you please revert the linting/formatting changes included in the PR so it is focused on the requested change?

As for the button changes, is it possible to make the button keep the same size when it changes to "copied"?

2022-08-26 07:07 UTC, sleepyqadir commented
@frangio reverted the linting/formatting changes and button width is now made fixed on trigger

2022-08-26 17:28 UTC, frangio commented
- Reverted some further linting.
- Refactored a little to use a boolean, so the UI text is defined in the template part of the Svelte component.

2022-08-26 17:29 UTC, frangio approved these changes

2022-08-26 17:32 UTC, merged